# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "1jwpnOa48Xmj92eh7MNb6bNxMzAqycAWKdEgLqO3aGFfP144xJeeQiXZzO+5dR2/NgaeumxV682xqu1YRaKcKy3qDzaX02E2aG8b3QIWgRm/Djpg/7N5RdSq85UQk+tByBGgAyc93b6x+5BAcorVcMKtfOlYrjnjE0pVBj7w4mRt85oKQg90DQFhHiVYjsKNfK6RFsJWICYdMDkWgfLH8AQtC8zryESDUeJDhKpZY3Vcll/cqq2mfXonq71DUKhbeqRyg4W4xrs24EFqgs0OC5eTzLczY90PWdHIXSyfR0ntg2ySDSYXMhk+LE+qATn+9A90MBSuyQmE6zarEUZKbRGaXhnh/tlx4ne6KsLlHdXrk1sgMw7U7b5NnZtUcKYddLJEv4BBEvP70GU0nrfe5h7O4ymHmtCbkOOAj4ORrLNvcetiNB3KJGUhpl3fair//3dy09LeE+cbt3hncJRxEeKe7UK6KmzdVkelWCHa55FtGL/QhkNDnAELJc4A1KQu1B6HVhA1inJpP47QkBeRGkUynC5pOHFcook950JrOYL8bY/KtShvEDMUnYHmyJAC2DI635xdNkhKmDo5vqeecn9/YjEntjAQsb+NRUl4npUAgAu3USarnj2pa364h9XWjh3SlBhiqaKIzLJbf8jTXsxDzkcyYoFrXuAUx/GyBkU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
