appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 1jwpnOa48Xmj92eh7MNb6bNxMzAqycAWKdEgLqO3aGFfP144xJeeQiXZzO+5dR2/NgaeumxV682xqu1YRaKcKy3qDzaX02E2aG8b3QIWgRm/Djpg/7N5RdSq85UQk+tByBGgAyc93b6x+5BAcorVcMKtfOlYrjnjE0pVBj7w4mRt85oKQg90DQFhHiVYjsKNfK6RFsJWICYdMDkWgfLH8AQtC8zryESDUeJDhKpZY3Vcll/cqq2mfXonq71DUKhbeqRyg4W4xrs24EFqgs0OC5eTzLczY90PWdHIXSyfR0ntg2ySDSYXMhk+LE+qATn+9A90MBSuyQmE6zarEUZKbRGaXhnh/tlx4ne6KsLlHdXrk1sgMw7U7b5NnZtUcKYddLJEv4BBEvP70GU0nrfe5h7O4ymHmtCbkOOAj4ORrLNvcetiNB3KJGUhpl3fair//3dy09LeE+cbt3hncJRxEeKe7UK6KmzdVkelWCHa55FtGL/QhkNDnAELJc4A1KQu1B6HVhA1inJpP47QkBeRGkUynC5pOHFcook950JrOYL8bY/KtShvEDMUnYHmyJAC2DI635xdNkhKmDo5vqeecn9/YjEntjAQsb+NRUl4npUAgAu3USarnj2pa364h9XWjh3SlBhiqaKIzLJbf8jTXsxDzkcyYoFrXuAUx/GyBkU=}
conda_forge_output_validation: true
