travis:
  secure:
    BINSTAR_TOKEN: K8tGxRfLBspUrBnEcIxJiBsXzsLLbnOnX5MmpHNcpsX/mLoWJyRrF2jzZxzU6NQnGqg/YkvzkgR+9uuFdYpBPGsebL7GynqUAbm+fYx8F7+FNHGfINZ3tRvk8/HQE3RzPrbURVXi7MkE+OWERND/5DlUs++/cjnhzNzE7mZar+lTyWUyie3SpCvbTkGWCek3VFUndNlPe08Qk+RVOAlFHdeOlf7fojlO//CPjoyRPhoWJj0ED8UtlwcaiAH8zMAFThjPdk4IL6BAvKxToWlFd0rOUaOtc2gAGE7E3dZoDF1NPt3NuFFGoehAQxP3HxVZMHS1hU5yUKYeMuXK79TRQ7pERU6kSfAubCGXmOfShtoLkr8/aCS63mFf0VOy4TPZgRZmibyv/VVyMXd3lO7D3WXa9OLsm1kreS705bYzfmlkCF8b+86NsugUW7OEwaSAP8QYgkQIYATwRgj5j/UiFndKRMqoS8IC6liEUKuRaz7Jj9rBHohmdH1gbrfSQh8/q7YmnQRT2Ylq5v5GRk8u4TL8mV6XjJjkIz58vs4a0VFUEPHM0EUnPJZXixNay0f0a+fK0PKH+yr1wLWpCYYGQg/TYJLvh5/pJebEUl12L5v92nG2E08Bzi0U7Zs2f1SsK2LJS6gyQI4URa+7fITQeWdYA7ctJEznOPUpyH4jR0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
